wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700226098.259049
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      - 105
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      - 74
      - 105
      3:
      - 23
      4: 3.10.12
      5: 0.16.0
      8:
      - 2
      - 5
      - 13
      13: linux-x86_64
